### ISSUE TITLE
OMG

### ISSUE THREAD

**Issue by mehranj73** [Douile/fnbr-api#2]
AttributeError: module 'fnbr' has no attribute 'STAT_TYPE'

**Comment by Douile** [comment]
@mehranj73 could you give more context e.g. line that caused the issue

**Comment by mehranj73** [comment]
if response.status == 200 and response.type == fnbr.STAT_TYPE:     This line
Pycharm shows STAT_TYPE with different color and i get "module 'fnbr' has no attribute 'STAT_TYPE'" error.
Also i get the same kind of error for image but not for shop.
I also tried writing STATS_TYPE.
Thank you.

**Comment by Douile** [comment]
@mehranj73 thanks for reporting. This was a typo on my part, you would actually use `fnbr.constants.STATS_TYPE`. Sorry about this I have updated [readme.md](/readme.md) to the proper usage.
